title: "Raúl González Cruz"
email: raul.gonzalezcz@udlap.mx
description: >- # this means to ignore newlines until "baseurl:"
  Hi there! This is my portfolio. Enjoy it!
baseurl: "/" 
url: "https://robbie.dev/" 
twitter_username: raulgonzalezcz
github_username:  raulgonzalezcz

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
